-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 18:15:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myfinancialcontrol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myfinancialcontrol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myfinancialcontrol` DEFAULT CHARACTER SET utf8 ;
USE `myfinancialcontrol` ;

-- -----------------------------------------------------
-- Table `myfinancialcontrol`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfinancialcontrol`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myfinancialcontrol`.`Register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfinancialcontrol`.`Register` (
  `idRegister` INT NOT NULL AUTO_INCREMENT,
  `register_date` VARCHAR(45) NULL,
  `value` DECIMAL NULL,
  `description` VARCHAR(100) NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`idRegister`),
  INDEX `fk_Register_Category_idx` (`idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_Register_Category`
    FOREIGN KEY (`idCategory`)
    REFERENCES `myfinancialcontrol`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
